version: "3.8"
services:
  server:
    image: anzlc/fuck-easistent:dev
    ports:
      - 8080:80
    environment:
      ADMIN_PASSWORD: testpassword
      CHECK_INTERVAL_SECONDS: 60
      CHECK_FULL_INTERVAL_SECONDS: 3600
    volumes:
      - db_data:/app/data
    restart: unless-stopped

volumes:
  db_data: